In [10]:
import pandas as pd

degree_jobs = pd.read_csv("../data/ai_jobs_dataset.csv")
degree_jobs.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [13]:
# Find how many Data Analyst jobs are in the job_title column
data_analyst_count = degree_jobs[degree_jobs['job_title'] == 'Data Analyst'].shape[0]
print(f"Number of 'Data Analyst' roles: {data_analyst_count}")

Number of 'Data Analyst' roles: 759

In [14]:
degree_jobs[degree_jobs['job_title'] == 'Data Analyst'].head(10)

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
8,AI00009,Data Analyst,160710,USD,SE,CT,Singapore,L,Singapore,0,"Hadoop, Git, Mathematics, Python",PhD,7,Government,2024-11-04,2024-11-24,551,9.3,Quantum Computing Inc
27,AI00028,Data Analyst,52997,USD,MI,PT,Austria,M,Singapore,0,"Mathematics, Kubernetes, TensorFlow, Tableau, ...",PhD,2,Government,2025-01-10,2025-02-20,2101,8.6,Predictive Systems
80,AI00081,Data Analyst,157597,EUR,EX,CT,France,L,France,50,"Git, Kubernetes, TensorFlow, R, Java",Bachelor,17,Manufacturing,2024-08-31,2024-09-15,639,8.4,Neural Networks Co
91,AI00092,Data Analyst,97997,EUR,SE,CT,France,S,France,50,"Hadoop, Python, TensorFlow, R, Statistics",PhD,8,Technology,2024-06-19,2024-07-16,2419,6.0,Algorithmic Solutions
96,AI00097,Data Analyst,109029,EUR,SE,FT,France,S,France,0,"Kubernetes, Scala, Java",Bachelor,6,Technology,2025-04-05,2025-06-13,2049,6.1,Predictive Systems
102,AI00103,Data Analyst,91577,EUR,MI,CT,Netherlands,M,Netherlands,100,"Spark, Mathematics, PyTorch, SQL, TensorFlow",Bachelor,3,Transportation,2024-01-27,2024-02-28,859,6.5,Algorithmic Solutions
117,AI00118,Data Analyst,65570,USD,SE,FL,Ireland,S,Ireland,50,"PyTorch, SQL, MLOps, AWS, TensorFlow",Associate,7,Retail,2024-10-22,2024-11-06,635,9.9,Smart Analytics
152,AI00153,Data Analyst,184637,USD,EX,PT,Sweden,S,Sweden,100,"R, SQL, Data Visualization",Bachelor,11,Government,2024-05-23,2024-07-09,2292,5.5,Machine Intelligence Group
209,AI00210,Data Analyst,48892,EUR,EN,CT,France,M,Ireland,100,"Linux, Python, NLP",Bachelor,0,Consulting,2024-10-08,2024-12-09,2296,6.6,DataVision Ltd
228,AI00229,Data Analyst,52027,USD,MI,PT,South Korea,M,South Korea,100,"Kubernetes, Linux, Tableau, MLOps, Statistics",Master,2,Retail,2024-04-18,2024-05-18,2036,5.7,Smart Analytics

In [15]:
data_analyst_jobs = degree_jobs[degree_jobs['job_title'] == 'Data Analyst']

In [16]:
data_analyst_jobs.isnull().sum()

job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

In [17]:
data_analyst_jobs.info()

<class 'pandas.DataFrame'>
Index: 759 entries, 8 to 14982
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  759 non-null    str
 1   job_title               759 non-null    str
 2   salary_usd              759 non-null    int64
 3   salary_currency         759 non-null    str
 4   experience_level        759 non-null    str
 5   employment_type         759 non-null    str
 6   company_location        759 non-null    str
 7   company_size            759 non-null    str
 8   employee_residence      759 non-null    str
 9   remote_ratio            759 non-null    int64
 10  required_skills         759 non-null    str
 11  education_required      759 non-null    str
 12  years_experience        759 non-null    int64
 13  industry                759 non-null    str
 14  posting_date            759 non-null    str
 15  application_deadline    759 non-null    str
 16  job_description_length  759 non-null    int64
 17  benefits_score          759 non-null    float64
 18  company_name            759 non-null    str
dtypes: float64(1), int64(4), str(14)
memory usage: 118.6 KB

In [20]:
# Define the columns to keep
columns_to_keep = [
    'job_title', 'salary_usd', 'employment_type', 'company_location', 'remote_ratio',
    'employee_residence', 'required_skills', 'education_required', 'posting_date', 'company_name']

data_analyst_jobs = data_analyst_jobs[columns_to_keep]
data_analyst_jobs.info()

<class 'pandas.DataFrame'>
Index: 759 entries, 8 to 14982
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_title           759 non-null    str
 1   salary_usd          759 non-null    int64
 2   employment_type     759 non-null    str
 3   company_location    759 non-null    str
 4   remote_ratio        759 non-null    int64
 5   employee_residence  759 non-null    str
 6   required_skills     759 non-null    str
 7   education_required  759 non-null    str
 8   posting_date        759 non-null    str
 9   company_name        759 non-null    str
dtypes: int64(2), str(8)
memory usage: 65.2 KB

In [21]:
# Renaming columns for consistency
data_analyst_jobs = data_analyst_jobs.rename(columns={
    'remote_ratio': 'is_remote',
    'employee_residence': 'employee_location',
    'required_skills': 'job_skills',
    'education_required': 'degree_required'
})
data_analyst_jobs.info()

<class 'pandas.DataFrame'>
Index: 759 entries, 8 to 14982
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   job_title          759 non-null    str
 1   salary_usd         759 non-null    int64
 2   employment_type    759 non-null    str
 3   company_location   759 non-null    str
 4   is_remote          759 non-null    int64
 5   employee_location  759 non-null    str
 6   job_skills         759 non-null    str
 7   degree_required    759 non-null    str
 8   posting_date       759 non-null    str
 9   company_name       759 non-null    str
dtypes: int64(2), str(8)
memory usage: 65.2 KB

In [22]:
degree_jobs = data_analyst_jobs.copy()

In [24]:
degree_jobs.info()

<class 'pandas.DataFrame'>
Index: 759 entries, 8 to 14982
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   job_title          759 non-null    str
 1   salary_usd         759 non-null    int64
 2   employment_type    759 non-null    str
 3   company_location   759 non-null    str
 4   is_remote          759 non-null    int64
 5   employee_location  759 non-null    str
 6   job_skills         759 non-null    str
 7   degree_required    759 non-null    str
 8   posting_date       759 non-null    str
 9   company_name       759 non-null    str
dtypes: int64(2), str(8)
memory usage: 65.2 KB